export const DISTRIBUTION_WORKFORCE_MENU_CODE = 'OP_DISTRIBUTION_WORKFORCE';

export const DISTRIBUTION_WORKFORCE_BASE_CERTIFICATE_NAME = '배전기능자격';

export const DISTRIBUTION_WORKFORCE_TARGETS = {
  noOutage: '무정전',
  underground: '지중배전',
} as const;

export const DISTRIBUTION_WORKFORCE_TARGET_NAMES = [
  DISTRIBUTION_WORKFORCE_TARGETS.noOutage,
  DISTRIBUTION_WORKFORCE_TARGETS.underground,
] as const;

export const DEFAULT_DISTRIBUTION_WORKFORCE_BATCH_LIMIT = 5;
export const DEFAULT_DISTRIBUTION_WORKFORCE_REQUEST_DELAY_MS = 800;
