export const SUNGWON_TAX_INVOICE_CONVERTER_MENU_CODE =
  'OP_SUNGWON_TAX_INVOICE_CONVERTER';

export const SUNGWON_COMPANY_DISPLAY_NAME = '성원전기㈜';

export const TAX_INVOICE_UPLOAD_MAX_SIZE = 10 * 1024 * 1024;
